name: tic_tac_toe_board_game
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.0

dependencies:
  cloud_firestore: ^6.4.1
  equatable: ^2.0.8
  firebase_core: ^4.9.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  gap: ^3.0.1
  google_fonts: ^8.1.0
  toastification: ^3.2.0

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets: 
    - assets/
