// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWwIF3QUmtmXCgMr3l4j2Sh7lRR-KIKO4',
    appId: '1:508866619487:web:464351150c9142d15853ea',
    messagingSenderId: '508866619487',
    projectId: 'tictactoeboard',
    authDomain: 'tictactoeboard.firebaseapp.com',
    storageBucket: 'tictactoeboard.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT6iupN5MfWQvr51uJF0lc8jh45M1ff18',
    appId: '1:508866619487:android:9c671c8524d4375b5853ea',
    messagingSenderId: '508866619487',
    projectId: 'tictactoeboard',
    storageBucket: 'tictactoeboard.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOSKFEnKvDDlHkFvqpyRljoG8FBYFUs94',
    appId: '1:508866619487:ios:16e8bac0340467205853ea',
    messagingSenderId: '508866619487',
    projectId: 'tictactoeboard',
    storageBucket: 'tictactoeboard.firebasestorage.app',
    iosBundleId: 'me.ankit.ticTacToeBoardGame',
  );
}
